//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoAutenticacao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int IdPessoa { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<long> CPF { get; set; }
        public string Nome { get; set; }
        public string Situacao { get; set; }
        public string ImagemPerfil { get; set; }
        public string FacebookID { get; set; }
        public string LinkedInID { get; set; }
        public string TwitterID { get; set; }
        public string Google_ID { get; set; }
        public string InstagramID { get; set; }
        public string Ativacao { get; set; }
    }
}
