//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoPublicacao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConexaoDemoTecnokratia : DbContext
    {
        public ConexaoDemoTecnokratia()
            : base("name=ConexaoDemoTecnokratia")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artigo> Artigo { get; set; }
        public DbSet<ProjetoLei> ProjetoLei { get; set; }
        public DbSet<PosicaoPolitica> PosicaoPolitica { get; set; }
        public DbSet<TipoProjeto> TipoProjeto { get; set; }
    }
}
