//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoDemokratia.ServicoAutenticacao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoServicoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoAutenticacao.TO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoAutenticacao.ListaPessoasTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoAutenticacao.PessoaTO))]
    public partial class RetornoServicoTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoFalhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SucessoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoFalha {
            get {
                return this.DescricaoFalhaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoFalhaField, value) != true)) {
                    this.DescricaoFalhaField = value;
                    this.RaisePropertyChanged("DescricaoFalha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoRetorno {
            get {
                return this.InfoRetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoRetornoField, value) != true)) {
                    this.InfoRetornoField = value;
                    this.RaisePropertyChanged("InfoRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sucesso {
            get {
                return this.SucessoField;
            }
            set {
                if ((this.SucessoField.Equals(value) != true)) {
                    this.SucessoField = value;
                    this.RaisePropertyChanged("Sucesso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaPessoasTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoAutenticacao.TO")]
    [System.SerializableAttribute()]
    public partial class ListaPessoasTO : TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnoDemokratia.ServicoAutenticacao.PessoaTO[] ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TechnoDemokratia.ServicoAutenticacao.PessoaTO[] Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoAutenticacao.TO")]
    [System.SerializableAttribute()]
    public partial class PessoaTO : TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Google_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAtivacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstagramIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedInIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwitterIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((this.CPFField.Equals(value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookID {
            get {
                return this.FacebookIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookIDField, value) != true)) {
                    this.FacebookIDField = value;
                    this.RaisePropertyChanged("FacebookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Google_ID {
            get {
                return this.Google_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Google_IDField, value) != true)) {
                    this.Google_IDField = value;
                    this.RaisePropertyChanged("Google_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAtivacao {
            get {
                return this.IdAtivacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAtivacaoField, value) != true)) {
                    this.IdAtivacaoField = value;
                    this.RaisePropertyChanged("IdAtivacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPessoa {
            get {
                return this.IdPessoaField;
            }
            set {
                if ((this.IdPessoaField.Equals(value) != true)) {
                    this.IdPessoaField = value;
                    this.RaisePropertyChanged("IdPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagemPerfil {
            get {
                return this.ImagemPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemPerfilField, value) != true)) {
                    this.ImagemPerfilField = value;
                    this.RaisePropertyChanged("ImagemPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramID {
            get {
                return this.InstagramIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstagramIDField, value) != true)) {
                    this.InstagramIDField = value;
                    this.RaisePropertyChanged("InstagramID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkedInID {
            get {
                return this.LinkedInIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedInIDField, value) != true)) {
                    this.LinkedInIDField = value;
                    this.RaisePropertyChanged("LinkedInID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwitterID {
            get {
                return this.TwitterIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitterIDField, value) != true)) {
                    this.TwitterIDField = value;
                    this.RaisePropertyChanged("TwitterID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mail.TipoEmail", Namespace="http://schemas.datacontract.org/2004/07/Utils.Mail")]
    public enum MailTipoEmail : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecuperacaoConta = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecuperacaoSenha = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmacao = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoAutenticacao.IInterfaceAutenticacao")]
    public interface IInterfaceAutenticacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/Autenticar", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AutenticarResponse")]
        TechnoDemokratia.ServicoAutenticacao.PessoaTO Autenticar(string Password, string userString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/Autenticar", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AutenticarResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.PessoaTO> AutenticarAsync(string Password, string userString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/AutenticarRedeSocial", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AutenticarRedeSocialResponse")]
        TechnoDemokratia.ServicoAutenticacao.PessoaTO AutenticarRedeSocial(string ID, string RedeSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/AutenticarRedeSocial", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AutenticarRedeSocialResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.PessoaTO> AutenticarRedeSocialAsync(string ID, string RedeSocial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/CadastrarSenhaCriptografadaRedeSocial", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/CadastrarSenhaCriptografadaRedeSocialRe" +
            "sponse")]
        TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO CadastrarSenhaCriptografadaRedeSocial(string IdRedeSocial, string RedeSocial, System.DateTime datacadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/CadastrarSenhaCriptografadaRedeSocial", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/CadastrarSenhaCriptografadaRedeSocialRe" +
            "sponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> CadastrarSenhaCriptografadaRedeSocialAsync(string IdRedeSocial, string RedeSocial, System.DateTime datacadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/IncluirNovoPessoa", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/IncluirNovoPessoaResponse")]
        TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO IncluirNovoPessoa(TechnoDemokratia.ServicoAutenticacao.PessoaTO PessoaTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/IncluirNovoPessoa", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/IncluirNovoPessoaResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> IncluirNovoPessoaAsync(TechnoDemokratia.ServicoAutenticacao.PessoaTO PessoaTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/EnviarEmailAutenticacao", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/EnviarEmailAutenticacaoResponse")]
        TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO EnviarEmailAutenticacao(TechnoDemokratia.ServicoAutenticacao.MailTipoEmail tpEmail, string Email, string Body, string linktramitacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/EnviarEmailAutenticacao", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/EnviarEmailAutenticacaoResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> EnviarEmailAutenticacaoAsync(TechnoDemokratia.ServicoAutenticacao.MailTipoEmail tpEmail, string Email, string Body, string linktramitacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/AlterarSenha", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AlterarSenhaResponse")]
        TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO AlterarSenha(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa, string senhaAntiga, string novaSenha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/AlterarSenha", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AlterarSenhaResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> AlterarSenhaAsync(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa, string senhaAntiga, string novaSenha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/AlterarSituacaoPessoa", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AlterarSituacaoPessoaResponse")]
        TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO AlterarSituacaoPessoa(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa, string p_situacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/AlterarSituacaoPessoa", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AlterarSituacaoPessoaResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> AlterarSituacaoPessoaAsync(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa, string p_situacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/ConsultarPerfil", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/ConsultarPerfilResponse")]
        TechnoDemokratia.ServicoAutenticacao.PessoaTO ConsultarPerfil(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/ConsultarPerfil", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/ConsultarPerfilResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.PessoaTO> ConsultarPerfilAsync(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/BuscarPessoa", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/BuscarPessoaResponse")]
        TechnoDemokratia.ServicoAutenticacao.ListaPessoasTO BuscarPessoa(string p_infoParcial, int p_index, int p_range);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/BuscarPessoa", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/BuscarPessoaResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.ListaPessoasTO> BuscarPessoaAsync(string p_infoParcial, int p_index, int p_range);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/AtivarUsuario", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AtivarUsuarioResponse")]
        bool AtivarUsuario(string codigoAtivacao, System.DateTime dataCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceAutenticacao/AtivarUsuario", ReplyAction="http://tempuri.org/IInterfaceAutenticacao/AtivarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> AtivarUsuarioAsync(string codigoAtivacao, System.DateTime dataCadastro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterfaceAutenticacaoChannel : TechnoDemokratia.ServicoAutenticacao.IInterfaceAutenticacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceAutenticacaoClient : System.ServiceModel.ClientBase<TechnoDemokratia.ServicoAutenticacao.IInterfaceAutenticacao>, TechnoDemokratia.ServicoAutenticacao.IInterfaceAutenticacao {
        
        public InterfaceAutenticacaoClient() {
        }
        
        public InterfaceAutenticacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceAutenticacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceAutenticacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceAutenticacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TechnoDemokratia.ServicoAutenticacao.PessoaTO Autenticar(string Password, string userString) {
            return base.Channel.Autenticar(Password, userString);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.PessoaTO> AutenticarAsync(string Password, string userString) {
            return base.Channel.AutenticarAsync(Password, userString);
        }
        
        public TechnoDemokratia.ServicoAutenticacao.PessoaTO AutenticarRedeSocial(string ID, string RedeSocial) {
            return base.Channel.AutenticarRedeSocial(ID, RedeSocial);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.PessoaTO> AutenticarRedeSocialAsync(string ID, string RedeSocial) {
            return base.Channel.AutenticarRedeSocialAsync(ID, RedeSocial);
        }
        
        public TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO CadastrarSenhaCriptografadaRedeSocial(string IdRedeSocial, string RedeSocial, System.DateTime datacadastro) {
            return base.Channel.CadastrarSenhaCriptografadaRedeSocial(IdRedeSocial, RedeSocial, datacadastro);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> CadastrarSenhaCriptografadaRedeSocialAsync(string IdRedeSocial, string RedeSocial, System.DateTime datacadastro) {
            return base.Channel.CadastrarSenhaCriptografadaRedeSocialAsync(IdRedeSocial, RedeSocial, datacadastro);
        }
        
        public TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO IncluirNovoPessoa(TechnoDemokratia.ServicoAutenticacao.PessoaTO PessoaTO) {
            return base.Channel.IncluirNovoPessoa(PessoaTO);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> IncluirNovoPessoaAsync(TechnoDemokratia.ServicoAutenticacao.PessoaTO PessoaTO) {
            return base.Channel.IncluirNovoPessoaAsync(PessoaTO);
        }
        
        public TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO EnviarEmailAutenticacao(TechnoDemokratia.ServicoAutenticacao.MailTipoEmail tpEmail, string Email, string Body, string linktramitacao) {
            return base.Channel.EnviarEmailAutenticacao(tpEmail, Email, Body, linktramitacao);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> EnviarEmailAutenticacaoAsync(TechnoDemokratia.ServicoAutenticacao.MailTipoEmail tpEmail, string Email, string Body, string linktramitacao) {
            return base.Channel.EnviarEmailAutenticacaoAsync(tpEmail, Email, Body, linktramitacao);
        }
        
        public TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO AlterarSenha(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa, string senhaAntiga, string novaSenha) {
            return base.Channel.AlterarSenha(p_pessoa, senhaAntiga, novaSenha);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> AlterarSenhaAsync(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa, string senhaAntiga, string novaSenha) {
            return base.Channel.AlterarSenhaAsync(p_pessoa, senhaAntiga, novaSenha);
        }
        
        public TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO AlterarSituacaoPessoa(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa, string p_situacao) {
            return base.Channel.AlterarSituacaoPessoa(p_pessoa, p_situacao);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.RetornoServicoTO> AlterarSituacaoPessoaAsync(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa, string p_situacao) {
            return base.Channel.AlterarSituacaoPessoaAsync(p_pessoa, p_situacao);
        }
        
        public TechnoDemokratia.ServicoAutenticacao.PessoaTO ConsultarPerfil(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa) {
            return base.Channel.ConsultarPerfil(p_pessoa);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.PessoaTO> ConsultarPerfilAsync(TechnoDemokratia.ServicoAutenticacao.PessoaTO p_pessoa) {
            return base.Channel.ConsultarPerfilAsync(p_pessoa);
        }
        
        public TechnoDemokratia.ServicoAutenticacao.ListaPessoasTO BuscarPessoa(string p_infoParcial, int p_index, int p_range) {
            return base.Channel.BuscarPessoa(p_infoParcial, p_index, p_range);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoAutenticacao.ListaPessoasTO> BuscarPessoaAsync(string p_infoParcial, int p_index, int p_range) {
            return base.Channel.BuscarPessoaAsync(p_infoParcial, p_index, p_range);
        }
        
        public bool AtivarUsuario(string codigoAtivacao, System.DateTime dataCadastro) {
            return base.Channel.AtivarUsuario(codigoAtivacao, dataCadastro);
        }
        
        public System.Threading.Tasks.Task<bool> AtivarUsuarioAsync(string codigoAtivacao, System.DateTime dataCadastro) {
            return base.Channel.AtivarUsuarioAsync(codigoAtivacao, dataCadastro);
        }
    }
}
