//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoVotacao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConexaoDemoTechnokratia : DbContext
    {
        public ConexaoDemoTechnokratia()
            : base("name=ConexaoDemoTechnokratia")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artigo> Artigo { get; set; }
        public DbSet<Pessoa> Pessoa { get; set; }
        public DbSet<Projeto> Projeto { get; set; }
        public DbSet<Voto> Voto { get; set; }
    }
}
