//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoVotacao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public int IdProjeto { get; set; }
        public string Descricao { get; set; }
        public int IdPessoa { get; set; }
        public Nullable<int> PorcentagemAprov { get; set; }
        public Nullable<int> PorcentagemReprov { get; set; }
        public string Situacao { get; set; }
        public int indiceAprov { get; set; }
        public string PosicaoPolitica { get; set; }
        public string Epigrafe { get; set; }
        public string Ementa { get; set; }
        public string Fecho { get; set; }
        public string Justificativa { get; set; }
        public string Preambulo { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    }
}
