//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoVotacao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voto
    {
        public int IdVoto { get; set; }
        public int IdPessoa { get; set; }
        public int IdArtigo { get; set; }
        public bool OpcaoVoto { get; set; }
    }
}
