//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoDemokratia.ServicoPublicacao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoServicoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoPublicacao.ListaArtigoTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoPublicacao.ArtigoTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoPublicacao.ProjetoTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoPublicacao.ListaProjetoTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoPublicacao.DetalhesProjetoTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoPublicacao.ListaTipoProjetoTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoPublicacao.ListaPosicaoPoliticaTO))]
    public partial class RetornoServicoTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoFalhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SucessoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoFalha {
            get {
                return this.DescricaoFalhaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoFalhaField, value) != true)) {
                    this.DescricaoFalhaField = value;
                    this.RaisePropertyChanged("DescricaoFalha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoRetorno {
            get {
                return this.InfoRetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoRetornoField, value) != true)) {
                    this.InfoRetornoField = value;
                    this.RaisePropertyChanged("InfoRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sucesso {
            get {
                return this.SucessoField;
            }
            set {
                if ((this.SucessoField.Equals(value) != true)) {
                    this.SucessoField = value;
                    this.RaisePropertyChanged("Sucesso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaArtigoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class ListaArtigoTO : TechnoDemokratia.ServicoPublicacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TechnoDemokratia.ServicoPublicacao.ArtigoTO> ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TechnoDemokratia.ServicoPublicacao.ArtigoTO> Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtigoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class ArtigoTO : TechnoDemokratia.ServicoPublicacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataMovimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdArtigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdArtigoSubstitutivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSugestaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Capitulo {
            get {
                return this.CapituloField;
            }
            set {
                if ((object.ReferenceEquals(this.CapituloField, value) != true)) {
                    this.CapituloField = value;
                    this.RaisePropertyChanged("Capitulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataMovimento {
            get {
                return this.DataMovimentoField;
            }
            set {
                if ((this.DataMovimentoField.Equals(value) != true)) {
                    this.DataMovimentoField = value;
                    this.RaisePropertyChanged("DataMovimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArtigo {
            get {
                return this.IdArtigoField;
            }
            set {
                if ((this.IdArtigoField.Equals(value) != true)) {
                    this.IdArtigoField = value;
                    this.RaisePropertyChanged("IdArtigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArtigoSubstitutivo {
            get {
                return this.IdArtigoSubstitutivoField;
            }
            set {
                if ((this.IdArtigoSubstitutivoField.Equals(value) != true)) {
                    this.IdArtigoSubstitutivoField = value;
                    this.RaisePropertyChanged("IdArtigoSubstitutivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPessoa {
            get {
                return this.IdPessoaField;
            }
            set {
                if ((this.IdPessoaField.Equals(value) != true)) {
                    this.IdPessoaField = value;
                    this.RaisePropertyChanged("IdPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProjeto {
            get {
                return this.IdProjetoField;
            }
            set {
                if ((this.IdProjetoField.Equals(value) != true)) {
                    this.IdProjetoField = value;
                    this.RaisePropertyChanged("IdProjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSugestao {
            get {
                return this.IsSugestaoField;
            }
            set {
                if ((this.IsSugestaoField.Equals(value) != true)) {
                    this.IsSugestaoField = value;
                    this.RaisePropertyChanged("IsSugestao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordem {
            get {
                return this.OrdemField;
            }
            set {
                if ((this.OrdemField.Equals(value) != true)) {
                    this.OrdemField = value;
                    this.RaisePropertyChanged("Ordem");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjetoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class ProjetoTO : TechnoDemokratia.ServicoPublicacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaminhoArquivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaminhoImagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndiceAprovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeracaoRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PorcentagemAprovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PorcentagemReprovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicaoPoliticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoProjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnoRegistro {
            get {
                return this.AnoRegistroField;
            }
            set {
                if ((this.AnoRegistroField.Equals(value) != true)) {
                    this.AnoRegistroField = value;
                    this.RaisePropertyChanged("AnoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaminhoArquivo {
            get {
                return this.CaminhoArquivoField;
            }
            set {
                if ((object.ReferenceEquals(this.CaminhoArquivoField, value) != true)) {
                    this.CaminhoArquivoField = value;
                    this.RaisePropertyChanged("CaminhoArquivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaminhoImagem {
            get {
                return this.CaminhoImagemField;
            }
            set {
                if ((object.ReferenceEquals(this.CaminhoImagemField, value) != true)) {
                    this.CaminhoImagemField = value;
                    this.RaisePropertyChanged("CaminhoImagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPessoa {
            get {
                return this.IdPessoaField;
            }
            set {
                if ((this.IdPessoaField.Equals(value) != true)) {
                    this.IdPessoaField = value;
                    this.RaisePropertyChanged("IdPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProjeto {
            get {
                return this.IdProjetoField;
            }
            set {
                if ((this.IdProjetoField.Equals(value) != true)) {
                    this.IdProjetoField = value;
                    this.RaisePropertyChanged("IdProjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndiceAprov {
            get {
                return this.IndiceAprovField;
            }
            set {
                if ((this.IndiceAprovField.Equals(value) != true)) {
                    this.IndiceAprovField = value;
                    this.RaisePropertyChanged("IndiceAprov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeracaoRegistro {
            get {
                return this.NumeracaoRegistroField;
            }
            set {
                if ((this.NumeracaoRegistroField.Equals(value) != true)) {
                    this.NumeracaoRegistroField = value;
                    this.RaisePropertyChanged("NumeracaoRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PorcentagemAprov {
            get {
                return this.PorcentagemAprovField;
            }
            set {
                if ((this.PorcentagemAprovField.Equals(value) != true)) {
                    this.PorcentagemAprovField = value;
                    this.RaisePropertyChanged("PorcentagemAprov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PorcentagemReprov {
            get {
                return this.PorcentagemReprovField;
            }
            set {
                if ((this.PorcentagemReprovField.Equals(value) != true)) {
                    this.PorcentagemReprovField = value;
                    this.RaisePropertyChanged("PorcentagemReprov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosicaoPolitica {
            get {
                return this.PosicaoPoliticaField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicaoPoliticaField, value) != true)) {
                    this.PosicaoPoliticaField = value;
                    this.RaisePropertyChanged("PosicaoPolitica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoProjeto {
            get {
                return this.TipoProjetoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoProjetoField, value) != true)) {
                    this.TipoProjetoField = value;
                    this.RaisePropertyChanged("TipoProjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaProjetoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class ListaProjetoTO : TechnoDemokratia.ServicoPublicacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TechnoDemokratia.ServicoPublicacao.ProjetoTO> ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TechnoDemokratia.ServicoPublicacao.ProjetoTO> Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalhesProjetoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class DetalhesProjetoTO : TechnoDemokratia.ServicoPublicacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaminhoImagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpigrafeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProjetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndiceAprovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JustificativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PorcentagemAprovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PorcentagemReprovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicaoPoliticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreambuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaminhoImagem {
            get {
                return this.CaminhoImagemField;
            }
            set {
                if ((object.ReferenceEquals(this.CaminhoImagemField, value) != true)) {
                    this.CaminhoImagemField = value;
                    this.RaisePropertyChanged("CaminhoImagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ementa {
            get {
                return this.EmentaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmentaField, value) != true)) {
                    this.EmentaField = value;
                    this.RaisePropertyChanged("Ementa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Epigrafe {
            get {
                return this.EpigrafeField;
            }
            set {
                if ((object.ReferenceEquals(this.EpigrafeField, value) != true)) {
                    this.EpigrafeField = value;
                    this.RaisePropertyChanged("Epigrafe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecho {
            get {
                return this.FechoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechoField, value) != true)) {
                    this.FechoField = value;
                    this.RaisePropertyChanged("Fecho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPessoa {
            get {
                return this.IdPessoaField;
            }
            set {
                if ((this.IdPessoaField.Equals(value) != true)) {
                    this.IdPessoaField = value;
                    this.RaisePropertyChanged("IdPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProjeto {
            get {
                return this.IdProjetoField;
            }
            set {
                if ((this.IdProjetoField.Equals(value) != true)) {
                    this.IdProjetoField = value;
                    this.RaisePropertyChanged("IdProjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndiceAprov {
            get {
                return this.IndiceAprovField;
            }
            set {
                if ((this.IndiceAprovField.Equals(value) != true)) {
                    this.IndiceAprovField = value;
                    this.RaisePropertyChanged("IndiceAprov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Justificativa {
            get {
                return this.JustificativaField;
            }
            set {
                if ((object.ReferenceEquals(this.JustificativaField, value) != true)) {
                    this.JustificativaField = value;
                    this.RaisePropertyChanged("Justificativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PorcentagemAprov {
            get {
                return this.PorcentagemAprovField;
            }
            set {
                if ((this.PorcentagemAprovField.Equals(value) != true)) {
                    this.PorcentagemAprovField = value;
                    this.RaisePropertyChanged("PorcentagemAprov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PorcentagemReprov {
            get {
                return this.PorcentagemReprovField;
            }
            set {
                if ((this.PorcentagemReprovField.Equals(value) != true)) {
                    this.PorcentagemReprovField = value;
                    this.RaisePropertyChanged("PorcentagemReprov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosicaoPolitica {
            get {
                return this.PosicaoPoliticaField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicaoPoliticaField, value) != true)) {
                    this.PosicaoPoliticaField = value;
                    this.RaisePropertyChanged("PosicaoPolitica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Preambulo {
            get {
                return this.PreambuloField;
            }
            set {
                if ((object.ReferenceEquals(this.PreambuloField, value) != true)) {
                    this.PreambuloField = value;
                    this.RaisePropertyChanged("Preambulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaTipoProjetoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class ListaTipoProjetoTO : TechnoDemokratia.ServicoPublicacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TechnoDemokratia.ServicoPublicacao.TipoProjetoTO> ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TechnoDemokratia.ServicoPublicacao.TipoProjetoTO> Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaPosicaoPoliticaTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class ListaPosicaoPoliticaTO : TechnoDemokratia.ServicoPublicacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TechnoDemokratia.ServicoPublicacao.PosicaoPoliticaTO> ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TechnoDemokratia.ServicoPublicacao.PosicaoPoliticaTO> Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoProjetoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class TipoProjetoTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbreviacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abreviacao {
            get {
                return this.AbreviacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.AbreviacaoField, value) != true)) {
                    this.AbreviacaoField = value;
                    this.RaisePropertyChanged("Abreviacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PosicaoPoliticaTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoPublicacao.TO")]
    [System.SerializableAttribute()]
    public partial class PosicaoPoliticaTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SituacaoProjeto", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum SituacaoProjeto : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CADASTRADO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VALIDADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATIVO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INATIVO = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENTADO = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REGISTRADO = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoPublicacao.IInterfacePublicacao")]
    public interface IInterfacePublicacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ConsultarHaSugestaoPessoa", ReplyAction="http://tempuri.org/IInterfacePublicacao/ConsultarHaSugestaoPessoaResponse")]
        TechnoDemokratia.ServicoPublicacao.RetornoServicoTO ConsultarHaSugestaoPessoa(int p_IdPessoa, int p_IdArtigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ConsultarHaSugestaoPessoa", ReplyAction="http://tempuri.org/IInterfacePublicacao/ConsultarHaSugestaoPessoaResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> ConsultarHaSugestaoPessoaAsync(int p_IdPessoa, int p_IdArtigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarArtigosSubstitutivosDoArtigo", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarArtigosSubstitutivosDoArtigoRespons" +
            "e")]
        TechnoDemokratia.ServicoPublicacao.ListaArtigoTO ListarArtigosSubstitutivosDoArtigo(int p_IdArtigo, int indice, int alcance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarArtigosSubstitutivosDoArtigo", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarArtigosSubstitutivosDoArtigoRespons" +
            "e")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaArtigoTO> ListarArtigosSubstitutivosDoArtigoAsync(int p_IdArtigo, int indice, int alcance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/PesquisarProjetos", ReplyAction="http://tempuri.org/IInterfacePublicacao/PesquisarProjetosResponse")]
        TechnoDemokratia.ServicoPublicacao.ListaProjetoTO PesquisarProjetos(TechnoDemokratia.ServicoPublicacao.ProjetoTO parametros, int indice, int alcance, System.Nullable<System.DateTime> rangeInicialDataCadastro, System.Nullable<System.DateTime> rangeFinalDataCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/PesquisarProjetos", ReplyAction="http://tempuri.org/IInterfacePublicacao/PesquisarProjetosResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaProjetoTO> PesquisarProjetosAsync(TechnoDemokratia.ServicoPublicacao.ProjetoTO parametros, int indice, int alcance, System.Nullable<System.DateTime> rangeInicialDataCadastro, System.Nullable<System.DateTime> rangeFinalDataCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/IncluirProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/IncluirProjetoResponse")]
        TechnoDemokratia.ServicoPublicacao.RetornoServicoTO IncluirProjeto(TechnoDemokratia.ServicoPublicacao.ProjetoTO p_ProjetoTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/IncluirProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/IncluirProjetoResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> IncluirProjetoAsync(TechnoDemokratia.ServicoPublicacao.ProjetoTO p_ProjetoTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/AnexarArquivoProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/AnexarArquivoProjetoResponse")]
        TechnoDemokratia.ServicoPublicacao.RetornoServicoTO AnexarArquivoProjeto(string TipoProjeto, int NumeroRegistro, int AnoRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/AnexarArquivoProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/AnexarArquivoProjetoResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> AnexarArquivoProjetoAsync(string TipoProjeto, int NumeroRegistro, int AnoRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarProjetos", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarProjetosResponse")]
        TechnoDemokratia.ServicoPublicacao.ListaProjetoTO ListarProjetos(int indice, int alcance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarProjetos", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarProjetosResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaProjetoTO> ListarProjetosAsync(int indice, int alcance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ConsultarProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/ConsultarProjetoResponse")]
        TechnoDemokratia.ServicoPublicacao.DetalhesProjetoTO ConsultarProjeto(int p_idProjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ConsultarProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/ConsultarProjetoResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.DetalhesProjetoTO> ConsultarProjetoAsync(int p_idProjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarTiposProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarTiposProjetoResponse")]
        TechnoDemokratia.ServicoPublicacao.ListaTipoProjetoTO ListarTiposProjeto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarTiposProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarTiposProjetoResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaTipoProjetoTO> ListarTiposProjetoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarArtigosdoProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarArtigosdoProjetoResponse")]
        TechnoDemokratia.ServicoPublicacao.ListaArtigoTO ListarArtigosdoProjeto(int p_idProjeto, int indice, int alcance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarArtigosdoProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarArtigosdoProjetoResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaArtigoTO> ListarArtigosdoProjetoAsync(int p_idProjeto, int indice, int alcance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/AlterarSituacaoProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/AlterarSituacaoProjetoResponse")]
        TechnoDemokratia.ServicoPublicacao.RetornoServicoTO AlterarSituacaoProjeto(TechnoDemokratia.ServicoPublicacao.SituacaoProjeto p_SituacaoProjeto, int p_idProjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/AlterarSituacaoProjeto", ReplyAction="http://tempuri.org/IInterfacePublicacao/AlterarSituacaoProjetoResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> AlterarSituacaoProjetoAsync(TechnoDemokratia.ServicoPublicacao.SituacaoProjeto p_SituacaoProjeto, int p_idProjeto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/IncluirSugestaoArtigo", ReplyAction="http://tempuri.org/IInterfacePublicacao/IncluirSugestaoArtigoResponse")]
        TechnoDemokratia.ServicoPublicacao.RetornoServicoTO IncluirSugestaoArtigo(int p_IdartigoPai, string p_Descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/IncluirSugestaoArtigo", ReplyAction="http://tempuri.org/IInterfacePublicacao/IncluirSugestaoArtigoResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> IncluirSugestaoArtigoAsync(int p_IdartigoPai, string p_Descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/DeletarArtigosObsoletos", ReplyAction="http://tempuri.org/IInterfacePublicacao/DeletarArtigosObsoletosResponse")]
        TechnoDemokratia.ServicoPublicacao.RetornoServicoTO DeletarArtigosObsoletos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/DeletarArtigosObsoletos", ReplyAction="http://tempuri.org/IInterfacePublicacao/DeletarArtigosObsoletosResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> DeletarArtigosObsoletosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarPosicoesPoliticas", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarPosicoesPoliticasResponse")]
        TechnoDemokratia.ServicoPublicacao.ListaPosicaoPoliticaTO ListarPosicoesPoliticas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacePublicacao/ListarPosicoesPoliticas", ReplyAction="http://tempuri.org/IInterfacePublicacao/ListarPosicoesPoliticasResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaPosicaoPoliticaTO> ListarPosicoesPoliticasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterfacePublicacaoChannel : TechnoDemokratia.ServicoPublicacao.IInterfacePublicacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfacePublicacaoClient : System.ServiceModel.ClientBase<TechnoDemokratia.ServicoPublicacao.IInterfacePublicacao>, TechnoDemokratia.ServicoPublicacao.IInterfacePublicacao {
        
        public InterfacePublicacaoClient() {
        }
        
        public InterfacePublicacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfacePublicacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfacePublicacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfacePublicacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TechnoDemokratia.ServicoPublicacao.RetornoServicoTO ConsultarHaSugestaoPessoa(int p_IdPessoa, int p_IdArtigo) {
            return base.Channel.ConsultarHaSugestaoPessoa(p_IdPessoa, p_IdArtigo);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> ConsultarHaSugestaoPessoaAsync(int p_IdPessoa, int p_IdArtigo) {
            return base.Channel.ConsultarHaSugestaoPessoaAsync(p_IdPessoa, p_IdArtigo);
        }
        
        public TechnoDemokratia.ServicoPublicacao.ListaArtigoTO ListarArtigosSubstitutivosDoArtigo(int p_IdArtigo, int indice, int alcance) {
            return base.Channel.ListarArtigosSubstitutivosDoArtigo(p_IdArtigo, indice, alcance);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaArtigoTO> ListarArtigosSubstitutivosDoArtigoAsync(int p_IdArtigo, int indice, int alcance) {
            return base.Channel.ListarArtigosSubstitutivosDoArtigoAsync(p_IdArtigo, indice, alcance);
        }
        
        public TechnoDemokratia.ServicoPublicacao.ListaProjetoTO PesquisarProjetos(TechnoDemokratia.ServicoPublicacao.ProjetoTO parametros, int indice, int alcance, System.Nullable<System.DateTime> rangeInicialDataCadastro, System.Nullable<System.DateTime> rangeFinalDataCadastro) {
            return base.Channel.PesquisarProjetos(parametros, indice, alcance, rangeInicialDataCadastro, rangeFinalDataCadastro);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaProjetoTO> PesquisarProjetosAsync(TechnoDemokratia.ServicoPublicacao.ProjetoTO parametros, int indice, int alcance, System.Nullable<System.DateTime> rangeInicialDataCadastro, System.Nullable<System.DateTime> rangeFinalDataCadastro) {
            return base.Channel.PesquisarProjetosAsync(parametros, indice, alcance, rangeInicialDataCadastro, rangeFinalDataCadastro);
        }
        
        public TechnoDemokratia.ServicoPublicacao.RetornoServicoTO IncluirProjeto(TechnoDemokratia.ServicoPublicacao.ProjetoTO p_ProjetoTO) {
            return base.Channel.IncluirProjeto(p_ProjetoTO);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> IncluirProjetoAsync(TechnoDemokratia.ServicoPublicacao.ProjetoTO p_ProjetoTO) {
            return base.Channel.IncluirProjetoAsync(p_ProjetoTO);
        }
        
        public TechnoDemokratia.ServicoPublicacao.RetornoServicoTO AnexarArquivoProjeto(string TipoProjeto, int NumeroRegistro, int AnoRegistro) {
            return base.Channel.AnexarArquivoProjeto(TipoProjeto, NumeroRegistro, AnoRegistro);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> AnexarArquivoProjetoAsync(string TipoProjeto, int NumeroRegistro, int AnoRegistro) {
            return base.Channel.AnexarArquivoProjetoAsync(TipoProjeto, NumeroRegistro, AnoRegistro);
        }
        
        public TechnoDemokratia.ServicoPublicacao.ListaProjetoTO ListarProjetos(int indice, int alcance) {
            return base.Channel.ListarProjetos(indice, alcance);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaProjetoTO> ListarProjetosAsync(int indice, int alcance) {
            return base.Channel.ListarProjetosAsync(indice, alcance);
        }
        
        public TechnoDemokratia.ServicoPublicacao.DetalhesProjetoTO ConsultarProjeto(int p_idProjeto) {
            return base.Channel.ConsultarProjeto(p_idProjeto);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.DetalhesProjetoTO> ConsultarProjetoAsync(int p_idProjeto) {
            return base.Channel.ConsultarProjetoAsync(p_idProjeto);
        }
        
        public TechnoDemokratia.ServicoPublicacao.ListaTipoProjetoTO ListarTiposProjeto() {
            return base.Channel.ListarTiposProjeto();
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaTipoProjetoTO> ListarTiposProjetoAsync() {
            return base.Channel.ListarTiposProjetoAsync();
        }
        
        public TechnoDemokratia.ServicoPublicacao.ListaArtigoTO ListarArtigosdoProjeto(int p_idProjeto, int indice, int alcance) {
            return base.Channel.ListarArtigosdoProjeto(p_idProjeto, indice, alcance);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaArtigoTO> ListarArtigosdoProjetoAsync(int p_idProjeto, int indice, int alcance) {
            return base.Channel.ListarArtigosdoProjetoAsync(p_idProjeto, indice, alcance);
        }
        
        public TechnoDemokratia.ServicoPublicacao.RetornoServicoTO AlterarSituacaoProjeto(TechnoDemokratia.ServicoPublicacao.SituacaoProjeto p_SituacaoProjeto, int p_idProjeto) {
            return base.Channel.AlterarSituacaoProjeto(p_SituacaoProjeto, p_idProjeto);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> AlterarSituacaoProjetoAsync(TechnoDemokratia.ServicoPublicacao.SituacaoProjeto p_SituacaoProjeto, int p_idProjeto) {
            return base.Channel.AlterarSituacaoProjetoAsync(p_SituacaoProjeto, p_idProjeto);
        }
        
        public TechnoDemokratia.ServicoPublicacao.RetornoServicoTO IncluirSugestaoArtigo(int p_IdartigoPai, string p_Descricao) {
            return base.Channel.IncluirSugestaoArtigo(p_IdartigoPai, p_Descricao);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> IncluirSugestaoArtigoAsync(int p_IdartigoPai, string p_Descricao) {
            return base.Channel.IncluirSugestaoArtigoAsync(p_IdartigoPai, p_Descricao);
        }
        
        public TechnoDemokratia.ServicoPublicacao.RetornoServicoTO DeletarArtigosObsoletos() {
            return base.Channel.DeletarArtigosObsoletos();
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.RetornoServicoTO> DeletarArtigosObsoletosAsync() {
            return base.Channel.DeletarArtigosObsoletosAsync();
        }
        
        public TechnoDemokratia.ServicoPublicacao.ListaPosicaoPoliticaTO ListarPosicoesPoliticas() {
            return base.Channel.ListarPosicoesPoliticas();
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoPublicacao.ListaPosicaoPoliticaTO> ListarPosicoesPoliticasAsync() {
            return base.Channel.ListarPosicoesPoliticasAsync();
        }
    }
}
