//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoDemokratia.ServicoArticulacao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoServicoTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoArticulacao.TO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoArticulacao.ReferenciaTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoArticulacao.ListaReferenciaTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TechnoDemokratia.ServicoArticulacao.ComentarioTO))]
    public partial class RetornoServicoTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoFalhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SucessoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoFalha {
            get {
                return this.DescricaoFalhaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoFalhaField, value) != true)) {
                    this.DescricaoFalhaField = value;
                    this.RaisePropertyChanged("DescricaoFalha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sucesso {
            get {
                return this.SucessoField;
            }
            set {
                if ((this.SucessoField.Equals(value) != true)) {
                    this.SucessoField = value;
                    this.RaisePropertyChanged("Sucesso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenciaTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoArticulacao.TO")]
    [System.SerializableAttribute()]
    public partial class ReferenciaTO : TechnoDemokratia.ServicoArticulacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkReferenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComentario {
            get {
                return this.IdComentarioField;
            }
            set {
                if ((this.IdComentarioField.Equals(value) != true)) {
                    this.IdComentarioField = value;
                    this.RaisePropertyChanged("IdComentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReferencia {
            get {
                return this.IdReferenciaField;
            }
            set {
                if ((this.IdReferenciaField.Equals(value) != true)) {
                    this.IdReferenciaField = value;
                    this.RaisePropertyChanged("IdReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkReferencia {
            get {
                return this.LinkReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkReferenciaField, value) != true)) {
                    this.LinkReferenciaField = value;
                    this.RaisePropertyChanged("LinkReferencia");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaReferenciaTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoArticulacao.TO")]
    [System.SerializableAttribute()]
    public partial class ListaReferenciaTO : TechnoDemokratia.ServicoArticulacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnoDemokratia.ServicoArticulacao.ReferenciaTO[] ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TechnoDemokratia.ServicoArticulacao.ReferenciaTO[] Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComentarioTO", Namespace="http://schemas.datacontract.org/2004/07/ServicoArticulacao.TO")]
    [System.SerializableAttribute()]
    public partial class ComentarioTO : TechnoDemokratia.ServicoArticulacao.RetornoServicoTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdArtigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdComentarioPaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArtigo {
            get {
                return this.IdArtigoField;
            }
            set {
                if ((this.IdArtigoField.Equals(value) != true)) {
                    this.IdArtigoField = value;
                    this.RaisePropertyChanged("IdArtigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComentario {
            get {
                return this.IdComentarioField;
            }
            set {
                if ((this.IdComentarioField.Equals(value) != true)) {
                    this.IdComentarioField = value;
                    this.RaisePropertyChanged("IdComentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComentarioPai {
            get {
                return this.IdComentarioPaiField;
            }
            set {
                if ((this.IdComentarioPaiField.Equals(value) != true)) {
                    this.IdComentarioPaiField = value;
                    this.RaisePropertyChanged("IdComentarioPai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPessoa {
            get {
                return this.IdPessoaField;
            }
            set {
                if ((this.IdPessoaField.Equals(value) != true)) {
                    this.IdPessoaField = value;
                    this.RaisePropertyChanged("IdPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordem {
            get {
                return this.OrdemField;
            }
            set {
                if ((this.OrdemField.Equals(value) != true)) {
                    this.OrdemField = value;
                    this.RaisePropertyChanged("Ordem");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoArticulacao.IInterfaceArticulacao")]
    public interface IInterfaceArticulacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/Comentar", ReplyAction="http://tempuri.org/IInterfaceArticulacao/ComentarResponse")]
        TechnoDemokratia.ServicoArticulacao.RetornoServicoTO Comentar(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_Comentario, TechnoDemokratia.ServicoArticulacao.ReferenciaTO[] p_referencias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/Comentar", ReplyAction="http://tempuri.org/IInterfaceArticulacao/ComentarResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> ComentarAsync(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_Comentario, TechnoDemokratia.ServicoArticulacao.ReferenciaTO[] p_referencias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/EditarComentario", ReplyAction="http://tempuri.org/IInterfaceArticulacao/EditarComentarioResponse")]
        TechnoDemokratia.ServicoArticulacao.RetornoServicoTO EditarComentario(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_comentarioTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/EditarComentario", ReplyAction="http://tempuri.org/IInterfaceArticulacao/EditarComentarioResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> EditarComentarioAsync(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_comentarioTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/RemoverComentario", ReplyAction="http://tempuri.org/IInterfaceArticulacao/RemoverComentarioResponse")]
        TechnoDemokratia.ServicoArticulacao.RetornoServicoTO RemoverComentario(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_comentarioTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/RemoverComentario", ReplyAction="http://tempuri.org/IInterfaceArticulacao/RemoverComentarioResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> RemoverComentarioAsync(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_comentarioTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/RemoverReferencia", ReplyAction="http://tempuri.org/IInterfaceArticulacao/RemoverReferenciaResponse")]
        TechnoDemokratia.ServicoArticulacao.RetornoServicoTO RemoverReferencia(TechnoDemokratia.ServicoArticulacao.ReferenciaTO p_ReferenciaTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/RemoverReferencia", ReplyAction="http://tempuri.org/IInterfaceArticulacao/RemoverReferenciaResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> RemoverReferenciaAsync(TechnoDemokratia.ServicoArticulacao.ReferenciaTO p_ReferenciaTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/IncluirReferencia", ReplyAction="http://tempuri.org/IInterfaceArticulacao/IncluirReferenciaResponse")]
        TechnoDemokratia.ServicoArticulacao.RetornoServicoTO IncluirReferencia(TechnoDemokratia.ServicoArticulacao.ReferenciaTO p_ReferenciaTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/IncluirReferencia", ReplyAction="http://tempuri.org/IInterfaceArticulacao/IncluirReferenciaResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> IncluirReferenciaAsync(TechnoDemokratia.ServicoArticulacao.ReferenciaTO p_ReferenciaTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/ConsultarComentario", ReplyAction="http://tempuri.org/IInterfaceArticulacao/ConsultarComentarioResponse")]
        TechnoDemokratia.ServicoArticulacao.ComentarioTO ConsultarComentario(int p_idArtigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/ConsultarComentario", ReplyAction="http://tempuri.org/IInterfaceArticulacao/ConsultarComentarioResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.ComentarioTO> ConsultarComentarioAsync(int p_idArtigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/ListarReferencias", ReplyAction="http://tempuri.org/IInterfaceArticulacao/ListarReferenciasResponse")]
        TechnoDemokratia.ServicoArticulacao.ListaReferenciaTO ListarReferencias(int p_idComentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfaceArticulacao/ListarReferencias", ReplyAction="http://tempuri.org/IInterfaceArticulacao/ListarReferenciasResponse")]
        System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.ListaReferenciaTO> ListarReferenciasAsync(int p_idComentario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterfaceArticulacaoChannel : TechnoDemokratia.ServicoArticulacao.IInterfaceArticulacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceArticulacaoClient : System.ServiceModel.ClientBase<TechnoDemokratia.ServicoArticulacao.IInterfaceArticulacao>, TechnoDemokratia.ServicoArticulacao.IInterfaceArticulacao {
        
        public InterfaceArticulacaoClient() {
        }
        
        public InterfaceArticulacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceArticulacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceArticulacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceArticulacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TechnoDemokratia.ServicoArticulacao.RetornoServicoTO Comentar(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_Comentario, TechnoDemokratia.ServicoArticulacao.ReferenciaTO[] p_referencias) {
            return base.Channel.Comentar(p_Comentario, p_referencias);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> ComentarAsync(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_Comentario, TechnoDemokratia.ServicoArticulacao.ReferenciaTO[] p_referencias) {
            return base.Channel.ComentarAsync(p_Comentario, p_referencias);
        }
        
        public TechnoDemokratia.ServicoArticulacao.RetornoServicoTO EditarComentario(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_comentarioTO) {
            return base.Channel.EditarComentario(p_comentarioTO);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> EditarComentarioAsync(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_comentarioTO) {
            return base.Channel.EditarComentarioAsync(p_comentarioTO);
        }
        
        public TechnoDemokratia.ServicoArticulacao.RetornoServicoTO RemoverComentario(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_comentarioTO) {
            return base.Channel.RemoverComentario(p_comentarioTO);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> RemoverComentarioAsync(TechnoDemokratia.ServicoArticulacao.ComentarioTO p_comentarioTO) {
            return base.Channel.RemoverComentarioAsync(p_comentarioTO);
        }
        
        public TechnoDemokratia.ServicoArticulacao.RetornoServicoTO RemoverReferencia(TechnoDemokratia.ServicoArticulacao.ReferenciaTO p_ReferenciaTO) {
            return base.Channel.RemoverReferencia(p_ReferenciaTO);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> RemoverReferenciaAsync(TechnoDemokratia.ServicoArticulacao.ReferenciaTO p_ReferenciaTO) {
            return base.Channel.RemoverReferenciaAsync(p_ReferenciaTO);
        }
        
        public TechnoDemokratia.ServicoArticulacao.RetornoServicoTO IncluirReferencia(TechnoDemokratia.ServicoArticulacao.ReferenciaTO p_ReferenciaTO) {
            return base.Channel.IncluirReferencia(p_ReferenciaTO);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.RetornoServicoTO> IncluirReferenciaAsync(TechnoDemokratia.ServicoArticulacao.ReferenciaTO p_ReferenciaTO) {
            return base.Channel.IncluirReferenciaAsync(p_ReferenciaTO);
        }
        
        public TechnoDemokratia.ServicoArticulacao.ComentarioTO ConsultarComentario(int p_idArtigo) {
            return base.Channel.ConsultarComentario(p_idArtigo);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.ComentarioTO> ConsultarComentarioAsync(int p_idArtigo) {
            return base.Channel.ConsultarComentarioAsync(p_idArtigo);
        }
        
        public TechnoDemokratia.ServicoArticulacao.ListaReferenciaTO ListarReferencias(int p_idComentario) {
            return base.Channel.ListarReferencias(p_idComentario);
        }
        
        public System.Threading.Tasks.Task<TechnoDemokratia.ServicoArticulacao.ListaReferenciaTO> ListarReferenciasAsync(int p_idComentario) {
            return base.Channel.ListarReferenciasAsync(p_idComentario);
        }
    }
}
