//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoArticulacao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int IdComentario { get; set; }
        public int IdArtigo { get; set; }
        public int IdPessoa { get; set; }
        public string Descricao { get; set; }
        public int Ordem { get; set; }
        public Nullable<int> IdComentarioPai { get; set; }
    }
}
