//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoArticulacao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referencia
    {
        public int IdReferencia { get; set; }
        public int IdComentario { get; set; }
        public string LinkReferencia { get; set; }
    }
}
